[package]
name = "gacha_tracker"
version = "1.3.0"
edition = "2021"
authors = ["WxWatch"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/WxWatch/gacha-tracker#readme"
repository = "https://github.com/WxWatch/gacha-tracker"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
shadow-rs = "0.24.1"
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
byteorder = "1.5.0"
form_urlencoded = "1.2.0"
futures = { version = "0.3.28", default-features = false, features = ["std", "async-await"] }
lazy_static = "1.4.0"
paste = "1.0.14"
reqwest = { version = "0.11.22", features = ["json", "stream"] }
sea-orm = { version = "0.12.3", features = ["sqlx-sqlite", "runtime-tokio", "macros", "runtime-tokio-native-tls"], default-features = false }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
shadow-rs = "0.24.1"
sqlx-core = "0.7.2"
tauri = { version = "1.5.1", features = ["clipboard-all", "dialog-all", "path-all", "process-all", "shell-all", "devtools"] }
thiserror = "1.0.49"
time = { version = "0.3.29", features = ["formatting", "serde", "macros", "serde-human-readable", "local-offset"] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.4.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
