[package]
name = "hoyo_gacha"
version = "0.3.0"
edition = "2021"
authors = ["lgou2w"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/lgou2w/HoYo.Gacha#readme"
repository = "https://github.com/lgou2w/HoYo.Gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
shadow-rs = "0.21.0"
tauri-build = { version = "1", features = [] }

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
byteorder = "1.4.3"
form_urlencoded = "1.1.0"
futures = { version = "0.3.28", default-features = false, features = ["std", "async-await"] }
lazy_static = "1.4.0"
paste = "1.0.12"
reqwest = { version = "0.11.18", features = ["json", "stream"] }
sea-orm = { version = "0.11.3", features = ["sqlx-sqlite", "runtime-tokio", "macros", "runtime-tokio-native-tls"], default-features = false }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
shadow-rs = "0.21.0"
sqlx-core = "0.6.3"
tauri = { version = "1.3.0", features = ["clipboard-all", "dialog-all", "path-all", "process-all", "shell-all"] }
thiserror = "1.0.40"
time = { version = "=0.3.15", features = ["formatting", "serde", "macros", "serde-human-readable", "local-offset"] }
tokio = { version = "1.28.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.3.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
